apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: local-dev
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.3.0
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            configMapKeyRef:
              name: airflow-config
              key: airflow.cfg
        volumeMounts:
        - name: dags-volume
          mountPath: /usr/local/dags
      volumes:
      - name: dags-volume
        hostPath:
          path: C:\Users\gaela\CKAD_Udemy\dags
          type: DirectoryOrCreate