apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: local-dev
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.3.0
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            configMapKeyRef:
              name: airflow-config
              key: airflow.cfg
        ports:
        - containerPort: 8080