apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: local-dev
data:
  airflow.cfg: |
    [core]
    executor = KubernetesExecutor
    load_examples = False
    dags_are_paused_at_creation = True
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres-service:5432/airflow
    [kubernetes]
    namespace = local-dev
    delete_worker_pods = True
    worker_container_repository = apache/airflow
    worker_container_tag = 2.3.0
    worker_container_image_pull_policy = IfNotPresent
    in_cluster = True
    [webserver]
    base_url = http://localhost:8080
    web_server_host = 0.0.0.0
    web_server_port = 8080

