apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - name: myvolume
      # directory location inside the pod
      mountPath: /usr/share/nginx/html
  volumes:
  - name: myvolume
    hostPath:
      # directory location on host
      path: /data/myfolder
      # this field is optional
      type: Directory