apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments/webserver-deployment.yaml
  - deployments/scheduler-deployment.yaml
  - deployments/postgres-deployment.yaml
  - services/webserver-service.yaml
  - services/postgres-service.yaml
  - configmaps/configmap.yaml