apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: airflow-webserver
      namespace: local-dev
    path: patch_webserver_deployment.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: airflow-scheduler
      namespace: local-dev
    path: patch_scheduler_deployment.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: postgres
      namespace: local-dev
    path: patch_postgres_deployment.yaml